version: "3.9"
   
services:
  web:
    build: .
    command: python manage.py runserver  0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    environment: 
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"


  